# Generated by Django 5.0.6 on 2024-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile_mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student')),
                ('file', models.FileField(upload_to='pdf')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
