# Generated by Django 5.0.6 on 2024-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_student_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_mobile',
            field=models.CharField(max_length=100),
        ),
    ]
