# Generated by Django 5.0.6 on 2024-08-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_products_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
