# Generated by Django 5.0.6 on 2024-08-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-price',)},
        ),
    ]
