# Generated by Django 5.0.6 on 2024-08-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-price',), 'verbose_name': 'Book', 'verbose_name_plural': 'Book'},
        ),
    ]
