# Generated by Django 5.0.6 on 2024-08-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_book_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('brand_name', 'country')},
        ),
    ]
