# Generated by Django 5.0.6 on 2024-08-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_brand_unique_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='brand',
            index_together={('brand_name', 'country')},
        ),
    ]
